spring:
  application:
    name: hamro-chalchitraghar-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/hamro_chalachitraghar_db
    username: postgres
    password: Himal123!
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
