package com.chalchitraghar.modules.audit.dto.request;

import com.chalchitraghar.modules.audit.enums.*;
import java.time.LocalDateTime;

public record AdminAuditLogFilterRequest(
        Long actorUserId,
        String actorEmail,
        String actorRole,
        AuditActorType actorType,
        AuditAction action,
        AuditCategory category,
        AuditSeverity severity,
        AuditResult result,
        String resourceType,
        Long resourceId,
        String resourceReference,
        String requestId,
        String correlationId,
        String httpMethod,
        String requestPath,
        LocalDateTime occurredFrom,
        LocalDateTime occurredTo,
        LocalDateTime createdFrom,
        LocalDateTime createdTo,
        Boolean hasBeforeValues,
        Boolean hasAfterValues,
        Boolean hasMetadata,
        Boolean systemOnly,
        Boolean externalOnly,
        Boolean deniedOnly,
        Boolean highRiskOnly) {
    public AdminAuditLogFilterRequest(
            Long actorUserId,
            String actorEmail,
            String actorRole,
            AuditActorType actorType,
            AuditAction action,
            AuditCategory category,
            AuditSeverity severity,
            AuditResult result,
            String resourceType,
            Long resourceId,
            String resourceReference,
            String requestId,
            String correlationId,
            String httpMethod,
            String requestPath,
            LocalDateTime occurredFrom,
            LocalDateTime occurredTo) {
        this(
                actorUserId,
                actorEmail,
                actorRole,
                actorType,
                action,
                category,
                severity,
                result,
                resourceType,
                resourceId,
                resourceReference,
                requestId,
                correlationId,
                httpMethod,
                requestPath,
                occurredFrom,
                occurredTo,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }
}
