package com.chalchitraghar.modules.tickets.service.impl;
import java.time.*; import org.springframework.data.domain.PageRequest; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.chalchitraghar.modules.tickets.config.*; import com.chalchitraghar.modules.tickets.dto.response.*; import com.chalchitraghar.modules.tickets.entity.*; import com.chalchitraghar.modules.tickets.enums.*; import com.chalchitraghar.modules.tickets.mapper.TicketMapper; import com.chalchitraghar.modules.tickets.repository.*; import com.chalchitraghar.modules.tickets.service.*; import com.chalchitraghar.modules.users.entity.User; import com.chalchitraghar.shared.exception.*; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor
public class TicketOperationsServiceImpl implements TicketOperationsService {
 private final TicketRepository tickets; private final TicketValidationRepository validations; private final TicketMapper mapper; private final TicketLifecycleService lifecycle; private final QrTokenService qr; private final Clock clock; private final TicketOperationsProperties props; private final TicketQrProperties qrProps;
 @Transactional public AdminTicketDetailResponse revoke(String ref,String reason,User admin){Ticket t=lock(ref);if(t.getStatus()==TicketStatus.REVOKED)return detail(t);if(t.getStatus()!=TicketStatus.ISSUED)throw new InvalidBookingStateException("Only an ISSUED ticket can be revoked");String r=required(reason);lifecycle.transition(t,TicketStatus.REVOKED);t.setRevokedAt(LocalDateTime.now(clock));t.setRevokedBy(admin);t.setRevocationReason(r);tickets.save(t);return detail(t);}
 @Transactional public AdminTicketDetailResponse reissue(String ref,String reason,User admin){Ticket t=lock(ref);if(t.getStatus()!=TicketStatus.ISSUED)throw new InvalidBookingStateException("Only an ISSUED ticket can be reissued");var token=qr.prepareToken();while(tickets.existsByQrTokenHash(token.tokenHash()))token=qr.prepareToken();t.setQrTokenEncrypted(token.encryptedToken());t.setQrTokenHash(token.tokenHash());t.setQrTokenVersion(t.getQrTokenVersion()+1);LocalDateTime now=LocalDateTime.now(clock);t.setQrIssuedAt(now);t.setReissuedAt(now);t.setReissuedBy(admin);t.setReissueReason(clean(reason));tickets.save(t);return detail(t);}
 @Transactional public int expireBatch(){LocalDateTime now=LocalDateTime.now(clock);var due=tickets.findIssuedDueForExpiry(now.toLocalDate(),PageRequest.of(0,props.expiryBatchSize()));int n=0;for(Ticket t:due){LocalDateTime end=LocalDateTime.of(t.getBooking().getShow().getShowDate(),t.getBooking().getShow().getEndTime()).plusMinutes(qrProps.postShowGraceMinutes());if(now.isAfter(end)){lifecycle.transition(t,TicketStatus.EXPIRED);t.setExpiredAt(now);n++;}}tickets.saveAll(due);return n;}
 @Transactional public void revokeForBooking(Long id,String reason,User actor){for(Ticket t:tickets.findByBookingIdForUpdate(id)){revokeOne(t,reason,actor);}}
 @Transactional public void revokeForShow(Long id,String reason,User actor){for(Ticket t:tickets.findByBookingShowIdForUpdate(id)){revokeOne(t,reason,actor);}}
 private void revokeOne(Ticket t,String reason,User actor){if(t.getStatus()==TicketStatus.CHECKED_IN)throw new InvalidBookingStateException("Checked-in tickets require manual review before cancellation");if(t.getStatus()==TicketStatus.ISSUED){lifecycle.transition(t,TicketStatus.REVOKED);t.setRevokedAt(LocalDateTime.now(clock));t.setRevokedBy(actor);t.setRevocationReason(reason);tickets.save(t);}}
 private Ticket lock(String r){return tickets.findByTicketReferenceForUpdate(r.trim().toUpperCase()).orElseThrow(()->new ResourceNotFoundException("Ticket not found with reference: "+r));}
 private String required(String r){String x=clean(r);if(x==null||x.isBlank())throw new IllegalArgumentException("Revocation reason is required");return x;}
 private String clean(String r){return r==null?null:r.trim();}
 private AdminTicketDetailResponse detail(Ticket t){return mapper.toAdminDetail(t,validations.findByTicketIdOrderByValidationTimeDesc(t.getId()));}
}
